# compose only meant for local development and testing and is not intended for production use in the cluster.
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: pwd
      MONGO_INITDB_DATABASE: todos

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://dev:pwd@mongo:27017/
      SECRET_KEY: dioqu3980d32dnjc83
    depends_on:
      - mongo
    restart: on-failure
