services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongo
    restart: on-failure
    

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PWD}
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

volumes:
  mongo: