services:
  mongo:
    image: mongo:7.0.9-jammy
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    env_file:
      - .env.dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PWD}
    restart: on-failure

volumes:
  mongo:
