name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
    # tests:
    #   runs-on: ubuntu-latest
    #   steps:
    #       - name: Checkout repository
    #         uses: actions/checkout@v4

    #       - name: Set up Python
    #         uses: actions/setup-python@v5
    #         with:
    #           python-version: '3.12'
    #           cache: 'pip'
    #       - run: pip install -r requirements.txt


    #       - name: Run tests
    #         run: pytest testing/*


    #       - name: Start services
    #         run: docker-compose up -d
          
    #       - name: Wait for the service to be ready
    #         run: |
    #           echo "Waiting for the service to be ready..."
    #           sleep 10

    #       - name: Run e2e tests
    #         run: ./e2e_tests.sh
            
    publish_and_deploy:
      if: github.event_name == 'push'
      runs-on: ubuntu-latest  
      # needs: tests
      steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Get version from commit tag
            id: version
            run: |
              echo "GITHUB_REF: ${GITHUB_REF}"
              if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
                echo "This is a tag: ${GITHUB_REF##*/}"
                echo TAG::${GITHUB_REF##*/} >> "$GITHUB_OUTPUT"
              else
                echo "This is not a tag, using"
                echo TAG::dev >> "$GITHUB_OUTPUT"
              fi

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v2
            with:
              aws-region: ap-south-1
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v1
            with:
             mask-password: 'true'

          - name: Build, tag, and push to ECR
            env:
              ECR_REGISTRY:  ${{ steps.login-ecr.outputs.registry }}
              ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
              IMAGE_TAG: ${{ steps.version.outputs.TAG }}
            run: |
              docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
              docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          - name: Checkout repository
            uses: actions/checkout@v4
            with:
              repository: 'Daniel-Portfolio/gitops'
              token: ${{ secrets.GH_TOKEN }}
              path: 'gitops'
          
          - name: update Charts.yaml
            run: |
              sed -i 's/appVersion:.*/appVersion: "${{ steps.version.outputs.TAG }}"/g' gitops/charts/todo-app/Chart.yaml
          
          - name: Commit changes
            env:
              GH_TOKEN: ${{ secrets.GH_TOKEN }}
            run: |
              cd gitops
              git config --local user.email "danirdd92@gmail.com"
              git config --local user.name "Daniel-Portfolio"
              git add gitops/charts/todo-app/Chart.yaml
              git commit -m "bump appVersion in Chart.yaml to ${{ steps.version.outputs.TAG }}"
              git push
              







